/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul7_2;

import javax.swing.JOptionPane;

/**
 *
 * @author Affandhy
 */
public class Frame2 extends javax.swing.JFrame {

    /**
     * Creates new form Frame2
     */
    public Frame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panjang = new javax.swing.JTextField();
        lebar = new javax.swing.JTextField();
        tinggi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        hitung = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        sisi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        volum = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jari = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        volume = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Program Penghitung Volume Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 20, 207, 14);

        jTabbedPane1.setFont(new java.awt.Font("Nirmala UI", 0, 20)); // NOI18N

        jPanel1.setLayout(null);

        jLabel2.setText("Panjang :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 29, 46, 14);

        jLabel3.setText("Lebar :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 67, 34, 14);

        jLabel4.setText("Tinggi :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 105, 35, 14);
        jPanel1.add(panjang);
        panjang.setBounds(116, 26, 130, 20);
        jPanel1.add(lebar);
        lebar.setBounds(116, 64, 130, 20);
        jPanel1.add(tinggi);
        tinggi.setBounds(116, 102, 130, 20);

        jLabel5.setText("cm");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(250, 29, 13, 14);

        jLabel6.setText("cm");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(250, 67, 13, 14);

        jLabel7.setText("cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(250, 105, 13, 14);

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        jPanel1.add(hitung);
        hitung.setBounds(116, 133, 63, 23);

        jTabbedPane1.addTab("Balok", jPanel1);

        jPanel2.setLayout(null);

        jLabel8.setText("Panjang SISI");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(60, 33, 62, 14);

        sisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sisiActionPerformed(evt);
            }
        });
        jPanel2.add(sisi);
        sisi.setBounds(60, 53, 67, 20);

        jLabel9.setText("cm");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(131, 56, 13, 14);

        volum.setText("Volume");
        volum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumActionPerformed(evt);
            }
        });
        jPanel2.add(volum);
        volum.setBounds(60, 91, 67, 23);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jLabel10.setText("Panjang jari-jari");

        jLabel11.setText("cm");

        volume.setText("Volume");
        volume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(volume)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jari))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(volume)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bola", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 40, 400, 260);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sisiActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        int Panjang, Lebar, Tinggi;
           Panjang = Integer.parseInt(panjang.getText());
           Lebar = Integer.parseInt(lebar.getText());
           Tinggi = Integer.parseInt(tinggi.getText());
           int hasil = Panjang * Lebar * Tinggi;
          try{
                JOptionPane.showMessageDialog(null,"Volume Balok ADALAH :" +hasil,"luas",
                        JOptionPane.INFORMATION_MESSAGE);
          } catch (Exception e){
                JOptionPane.showMessageDialog(null,"Error :" +e,"gagal",
                        JOptionPane.WARNING_MESSAGE);
          }
    }//GEN-LAST:event_hitungActionPerformed

    private void volumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumActionPerformed
        // TODO add your handling code here:
        int SISI;
        SISI = Integer.parseInt(sisi.getText());
        int hasil = SISI*SISI*SISI;
        try{
                JOptionPane.showMessageDialog(null,"Luas Permukaan kubus ADALAH :" +hasil,"luas",
                        JOptionPane.INFORMATION_MESSAGE);
          } catch (Exception e){
                JOptionPane.showMessageDialog(null,"Error :" +e,"gagal",
                        JOptionPane.WARNING_MESSAGE);
          }
    }//GEN-LAST:event_volumActionPerformed

    private void volumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumeActionPerformed
        // TODO add your handling code here:
        float JARI;
        JARI = Integer.parseInt(jari.getText());
        float hasil1 = (float) (4/3*3.14*JARI*JARI*JARI);
        try{
                JOptionPane.showMessageDialog(null,"Luas Permukaan Bola ADALAH :" +hasil1,"luas",
                        JOptionPane.INFORMATION_MESSAGE);
          } catch (Exception e){
                JOptionPane.showMessageDialog(null,"Error :" +e,"gagal",
                        JOptionPane.WARNING_MESSAGE);
          }
        
        
    }//GEN-LAST:event_volumeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jari;
    private javax.swing.JTextField lebar;
    private javax.swing.JTextField panjang;
    private javax.swing.JTextField sisi;
    private javax.swing.JTextField tinggi;
    private javax.swing.JButton volum;
    private javax.swing.JButton volume;
    // End of variables declaration//GEN-END:variables
}
